# Generated by Django 3.2.5 on 2021-08-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('fonction', models.CharField(choices=[('A', 'SOUS DIRECTEUR PERSONNEL'), ('C', 'CHEF ATS')], max_length=1)),
                ('profile_pic', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('function', models.CharField(choices=[('R', 'rien'), ('D', 'directeur'), ('DA', 'directeur adjoint'), ('SD', 'sous-directeur'), ('SDF', 'sous-directeur de finances')], max_length=3, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('naissance', models.DateField()),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('situation', models.CharField(choices=[('C', 'celibataire'), ('M', 'marié'), ('D', 'devorcé')], max_length=1, null=True)),
                ('date_joined', models.DateField()),
                ('date_recretment', models.DateField()),
                ('Nenfant', models.IntegerField()),
                ('nature', models.CharField(choices=[('S', 'stagiaire'), ('F', 'fonctionnaire')], max_length=1, null=True)),
                ('numccp', models.IntegerField()),
                ('numss', models.IntegerField()),
                ('Xfonctionnair', models.BooleanField(default=False)),
                ('motif', models.CharField(choices=[('N', 'None'), ('DE', 'Décédé'), ('M', 'Mutation'), ('DI', 'Dimensionné'), ('R', 'Retraité')], default='N', max_length=2)),
                ('date_supression', models.DateField(auto_now_add=True, null=True)),
                ('comentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_prime', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('trimestre', models.CharField(blank=True, choices=[('1', '1er trimestre'), ('2', '2eme trimestre'), ('3', '3eme trimestre'), ('4', '4eme trimestre')], max_length=1, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('salaire_principal', models.FloatField()),
                ('salaire_brut_mensulle', models.FloatField()),
                ('salaire_brut_trimi', models.FloatField()),
                ('securite_sociale', models.FloatField()),
                ('base_impot', models.FloatField()),
                ('irg', models.FloatField()),
                ('prime_net', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(choices=[('0', 'Filiere'), ('A', 'Administration'), ('I', 'Informatique')], default='0', max_length=1)),
                ('grade', models.CharField(choices=[('0', 'Grade'), ('GA', 'Adimistrateur'), ('GAP', 'Administrateur principal'), ('GAC', 'Administrateur conseiller'), ('GAA', "Attaché d'administration"), ('GPA', "Attaché principale d'administration"), ('AB', 'Agents de bureau'), ('AA', "Agent d'administration"), ('APA', "Agent principale d'administration"), ('AS', 'Agents de saisie'), ('S', 'Secretaire'), ('SD', 'Secretaire de direction'), ('SPD', 'Secretaire principale de direction'), ('ACA', 'Aide comptable administrative'), ('CA', 'Compatble administrative'), ('CAP', 'Comptable administrative principale'), ('IA', "Ingenieur d'application"), ('IE', "Ingenieur d'etat"), ('IP', 'Ingenieur principal'), ('IC', 'Ingenieur en chef'), ('T', 'Technicien'), ('TS', 'Technicien superieur'), ('AT', 'Adjoint technique'), ('AST', 'Agent technique')], default='0', max_length=3)),
                ('corps', models.CharField(choices=[('0', 'COPRS'), ('A', 'Adminstrateurs'), ('AD', "Attachés d'dministrations"), ('AA', "Agents d'dministrations"), ('S', 'Secretaire'), ('CA', 'Comptables administratifs'), ('I', 'Ingenieurs'), ('T', 'Techniciens'), ('AT', 'Adjoint techniques'), ('AST', 'Agents techniques')], default='0', max_length=3)),
                ('categorie', models.IntegerField(default=0)),
                ('indice', models.IntegerField(default=0)),
                ('salaire', models.FloatField(default=0.0)),
                ('poste_occupe', models.CharField(choices=[('R', 'Rien'), ('D', 'Directeur'), ('DA', 'Directeur adjoint'), ('CD', 'Chef de departement'), ('SG', 'Secretaire generale'), ('DB', 'Directeur de la bibliotheque'), ('SDPF', 'Sous directeur des personnels et de la formation'), ('SDFM', 'Sous directeur des finances et de moyens'), ('RCIA', "Responsable de centre d'impression et d'audiovisuel"), ('RCSI', "Responsable de centre de systemes et reseaux d'informations"), ('RHT', 'Responsable de hall de technologies'), ('RFP', 'Responsable de la forme de production')], default='R', max_length=4)),
                ('indiciaire', models.FloatField(default=0.0)),
                ('categorie_promo', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], default='0', max_length=2)),
                ('groupe', models.CharField(default='None', max_length=10)),
                ('indice_minimale', models.FloatField(default=0.0)),
                ('indice_echelon', models.CharField(choices=[('0', '0'), ('1', '1er'), ('2', '2eme'), ('3', '3eme'), ('4', '4eme'), ('5', '5eme'), ('6', '6eme'), ('7', '7eme'), ('8', '8eme'), ('9', '9eme'), ('10', '10eme'), ('11', '11eme'), ('12', '12eme')], default='0', max_length=2)),
                ('echelon', models.IntegerField(default=0)),
                ('grille', models.FloatField(default=0.0)),
                ('indemite_sac', models.FloatField(default=0.0)),
                ('indemite_stc', models.FloatField(default=0.0)),
                ('securite', models.FloatField(default=0.0)),
                ('salaire_brut', models.FloatField(default=0.0)),
                ('indimnite_transport', models.IntegerField(default=0)),
                ('indimnite_panier', models.IntegerField(default=0)),
                ('totale_brute_imposable_irg', models.FloatField(default=0.0)),
                ('irg', models.IntegerField(default=0)),
                ('allocation_familiale', models.IntegerField(default=0)),
                ('totale', models.FloatField(default=0.0)),
                ('nombre_travaille', models.IntegerField(default=0)),
                ('nombre_absence', models.IntegerField(default=0)),
                ('salaire_net', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('nature', models.CharField(blank=True, choices=[('M', 'Maladie'), ('A', 'Annuel'), ('E', 'Exceptionnel')], max_length=1, null=True)),
                ('retour', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
