# Generated by Django 3.2.5 on 2021-08-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_effet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='decision',
            field=models.CharField(choices=[('N', 'None'), ('A', 'Automatique'), ('C', 'Commission')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_greater_than_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_greater_than_2',
            field=models.BooleanField(default=False),
        ),
    ]
