# Generated by Django 3.2.5 on 2021-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210817_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cheked',
            field=models.BooleanField(default=False),
        ),
    ]
