# Generated by Django 3.2.5 on 2021-08-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_utilisateur_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('function', models.CharField(choices=[('R', 'rien'), ('D', 'directeur'), ('DA', 'directeur adjoint'), ('SD', 'sous-directeur'), ('SDF', 'sous-directeur de finances')], max_length=3, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('naissance', models.DateField()),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('situation', models.CharField(choices=[('C', 'celibataire'), ('M', 'marié'), ('D', 'devorcé')], max_length=1, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('Nenfant', models.IntegerField()),
                ('nature', models.CharField(choices=[('S', 'stagiaire'), ('F', 'fonctionnaire')], max_length=1, null=True)),
                ('numccp', models.IntegerField()),
                ('numss', models.IntegerField()),
                ('Xfonctionnair', models.BooleanField(default=False)),
            ],
        ),
    ]
