# Generated by Django 3.2.5 on 2021-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_recretment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
