# Generated by Django 3.2.5 on 2021-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_cheked'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alerte',
            field=models.CharField(blank=True, choices=[('1', '1 an'), ('2', '2 ans'), ('3', '3 ans'), ('4', '4 ans'), ('5', '5 ans'), ('6', '6 ans')], max_length=1, null=True),
        ),
    ]
