# Generated by Django 3.2.5 on 2021-08-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='alerte',
            field=models.CharField(choices=[('0', '0'), ('1', '1 an'), ('2', '2 ans'), ('3', '3 ans'), ('4', '4 ans'), ('5', '5 ans'), ('6', '6 ans')], default='0', max_length=1),
        ),
    ]
