# Generated by Django 3.2.5 on 2021-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_paie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paie',
            name='indemite_sac',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='indemite_stc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='indice_minimale',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='salaire_brut',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='salaire_net',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='securite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='totale',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='totale_brute_imposable_irg',
            field=models.FloatField(default=0.0),
        ),
    ]
