# Generated by Django 3.2.5 on 2021-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210808_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paie',
            name='grille',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='paie',
            name='indiciaire',
            field=models.FloatField(default=0.0),
        ),
    ]
