# Generated by Django 3.2.5 on 2021-08-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_conge_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
