# Generated by Django 3.2.5 on 2021-08-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_conge_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_principal', models.FloatField()),
                ('salaire_brut_mensulle', models.FloatField()),
                ('salaire_brut_trimi', models.FloatField()),
                ('securite_sociale', models.FloatField()),
                ('base_impot', models.FloatField()),
                ('irg', models.FloatField()),
                ('prime_net', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
