# Generated by Django 3.2.5 on 2021-08-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_paie_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='paie',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
    ]
