# Generated by Django 3.2.5 on 2021-08-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210811_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='nature',
            field=models.CharField(blank=True, choices=[('M', 'Maladie'), ('A', 'Annuel'), ('E', 'Exceptionnel')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
