# Generated by Django 3.2.5 on 2021-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210811_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='prime',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prime',
            name='note_prime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prime',
            name='trimestre',
            field=models.IntegerField(blank=True, choices=[('1', '1er trimestre'), ('2', '2eme trimestre'), ('3', '3eme trimestre'), ('4', '4eme trimestre')], null=True),
        ),
    ]
