# Generated by Django 3.2.5 on 2021-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_prime_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
