# Generated by Django 3.2.5 on 2021-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_paie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_supression',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='motif',
            field=models.CharField(choices=[('N', 'None'), ('DE', 'Décédé'), ('M', 'Mutation'), ('DI', 'Dimensionné'), ('R', 'Retraité')], default='N', max_length=2),
        ),
    ]
