# Generated by Django 3.2.5 on 2021-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210814_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(choices=[('A', 'SOUS DIRECTEUR PERSONNEL'), ('C', 'CHEF ATS')], max_length=1),
        ),
    ]
